### ISSUE TITLE
(find volunteer) Test all Opsis's, log in spreadsheet

### ISSUE THREAD

**Issue by mithro** [xfxf/lca2017-av#11]
Spreadsheet (results): https://docs.google.com/spreadsheets/d/1W3p1J-Lb6l-sWmh6n9-YJ_U5o7a0pDmWAR6QIKfCzI0/edit#gid=0

**Comment by mithro** [comment]
https://docs.google.com/spreadsheets/d/1W3p1J-Lb6l-sWmh6n9-YJ_U5o7a0pDmWAR6QIKfCzI0/edit#gid=0

**Comment by xfxf** [comment]
Tested 2 boards.  Need a volunteer to test the rest using the subset we have identified.  Followed the following steps:

* Take device to be tested, and first cable to test it with.  Plug into input0.
* Power cycle device (always do this for every cable, important).  Connect via serial, type ''debug on'.  
* Ensure displays picture OK, no WER errors.  Unplug cable, wait 6 seconds, plug back in, repeat 2-3 times.  If all OK, mark '1' in sheet.
* If one of the steps above failed, mark appropriate value (2, 3, 4) along with a few lines of 'debug on''s output showing WER errors or otherwise.  If "IDELAY busy timeout" ever shows, also include this in paste.  Paste in output of 'status' also.
* Power cycle device, connect via serial, 'debug on', see if the error noted above has changed or is the same.  Note this.
* Repeat above for input1.

* Repeat all of above for all cables for same device.

* Repeat all of the above for all devices for all cables.

**Comment by mithro** [comment]
I think we want each input tested with the following;
 * Ryan rMBP 2013 - mDP	RedMere, Crappy White
 * Ryan rMBP 2013 - HDMI	RedMere, Crappy White
 * VGA2HDMI (via T410)	RedMere

Ideally we would want to add but I'm happy to leave that to later...
 * XA20	RedMere - miniHDMI
 * JVC	RedMere

**Comment by xfxf** [comment]
We need to find a volunteer to help us do this (expected to take a few hours).  Have made a few calls, no bites yet.
